// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

library RoleIds {
    bytes32 internal constant ELIGIBILITY_OPERATOR_ROLE = keccak256("ELIGIBILITY_OPERATOR_ROLE");
    bytes32 internal constant EXECUTION_ALLOCATION_CONFIRMER_ROLE = keccak256("EXECUTION_ALLOCATION_CONFIRMER_ROLE");
    bytes32 internal constant RISK_APPROVER_ROLE = keccak256("RISK_APPROVER_ROLE");
    bytes32 internal constant RIGHTS_ENTRY_APPROVER_ROLE = keccak256("RIGHTS_ENTRY_APPROVER_ROLE");
    bytes32 internal constant RIGHTS_RECORDING_CONFIRMER_ROLE = keccak256("RIGHTS_RECORDING_CONFIRMER_ROLE");
    bytes32 internal constant SETTLEMENT_CONFIRMER_ROLE = keccak256("SETTLEMENT_CONFIRMER_ROLE");
    bytes32 internal constant CUSTODY_CONFIRMER_ROLE = keccak256("CUSTODY_CONFIRMER_ROLE");
    bytes32 internal constant ISSUANCE_EXECUTOR_ROLE = keccak256("ISSUANCE_EXECUTOR_ROLE");
    bytes32 internal constant SETTLEMENT_EXECUTOR_ROLE = keccak256("SETTLEMENT_EXECUTOR_ROLE");
    bytes32 internal constant REDEMPTION_RIGHTS_APPROVER_ROLE = keccak256("REDEMPTION_RIGHTS_APPROVER_ROLE");
    bytes32 internal constant PAYMENT_APPROVER_ROLE = keccak256("PAYMENT_APPROVER_ROLE");
    bytes32 internal constant REDEMPTION_EXECUTOR_ROLE = keccak256("REDEMPTION_EXECUTOR_ROLE");
    bytes32 internal constant RECOVERY_RIGHTS_APPROVER_ROLE = keccak256("RECOVERY_RIGHTS_APPROVER_ROLE");
    bytes32 internal constant RECOVERY_COMPLIANCE_APPROVER_ROLE = keccak256("RECOVERY_COMPLIANCE_APPROVER_ROLE");
    bytes32 internal constant RECOVERY_EXECUTOR_ROLE = keccak256("RECOVERY_EXECUTOR_ROLE");
    bytes32 internal constant CORPORATE_ACTION_RIGHTS_APPROVER_ROLE =
        keccak256("CORPORATE_ACTION_RIGHTS_APPROVER_ROLE");
    bytes32 internal constant CORPORATE_ACTION_AUDIT_APPROVER_ROLE = keccak256("CORPORATE_ACTION_AUDIT_APPROVER_ROLE");
    bytes32 internal constant CORPORATE_ACTION_EXECUTOR_ROLE = keccak256("CORPORATE_ACTION_EXECUTOR_ROLE");
    bytes32 internal constant EMERGENCY_PAUSER_ROLE = keccak256("EMERGENCY_PAUSER_ROLE");
}
